#!/usr/bin/env bash

# PhpStorm URL Handler
# phpstorm://open?url=file://@file&line=@line
# phpstorm://open?file=@file&line=@line
# phpstorm://open?url=file://@file:@line
# phpstorm://open?file=@file:line
#
# @license GPL
# @author Stefan Auditor <stefan@auditor.email>

function urldecode() { : "${*//+/ }"; echo -e "${_//%/\\x}"; }

arg=$(urldecode "${1}")

# Get the file path and line number using bash regex
if [[ "${arg}" =~ file(://|=)([^:&]+) ]]; then
    file="${BASH_REMATCH[2]}"
fi

if [[ "${arg}" =~ (:|&line=)([0-9]+) ]]; then
    line="${BASH_REMATCH[2]}"
fi

# Check if phpstorm|pstorm command exist.
if type phpstorm > /dev/null 2>&1; then
    if [ -z "${1}" ]; then
        /usr/bin/env phpstorm
    else
        /usr/bin/env phpstorm --line "${line}" "${file}"
    fi
fi

exit 0
